language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="ldap:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="ldap" OCAML_VERSION="4.02.3"
  - PACKAGE="ldap" OCAML_VERSION="4.03.0"
  - PACKAGE="ldap" OCAML_VERSION="4.04.2"
  - PACKAGE="ldap" OCAML_VERSION="4.05.0"
  - PACKAGE="ldap" OCAML_VERSION="4.06.1"
  - PACKAGE="ldap" OCAML_VERSION="4.07.1"
  - PACKAGE="ldap" OCAML_VERSION="4.08.1"
  - PACKAGE="ldap" OCAML_VERSION="4.09.0"
